language: ruby
before_install: gem install bundler -v '1.17.3'
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
install: bundle _1.17.3_ install --jobs=3 --retry=3
script: bundle exec rspec
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - ruby-head
env:
  global:
    - CI="travis"
    - MONGODB=4.0.1
  matrix:
    - OHMYLOG_ORM=active_record
    - OHMYLOG_ORM=mongoid
matrix:
  exclude:
    # Skip these combinations because they have incompatible dependencies
    # and will always fail.
    - rvm: 2.6.0
      gemfile: gemfiles/rails_4.2_stable.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.2_stable.gemfile
  #    - rvm: 2.3
  #      gemfile: gemfiles/rails_6.0_beta.gemfile
  #    - rvm: 2.4
  #      gemfile: gemfiles/rails_6.0_beta.gemfile
  allow_failures:
#    - gemfile: gemfiles/rails_6.0_beta.gemfile
#    - rvm: ruby-head
gemfile:
  - gemfiles/rails_4.2_stable.gemfile
  - gemfiles/rails_5.0_stable.gemfile
  - gemfiles/rails_5.1_stable.gemfile
  - gemfiles/rails_5.2_stable.gemfile
#  - gemfiles/rails_6.0_beta.gemfile