language: ruby
before_install: gem install bundler -v '1.17.3'
install: bundle _1.17.3_ install --jobs=3 --retry=3
script: bundle exec rspec
services:
  - mongodb
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.5.8
  - 2.6.6
  - 2.7.1
  #- ruby-head
env:
  matrix:
    - OHMYLOG_ORM=active_record
    - OHMYLOG_ORM=mongoid
matrix:
  exclude:
    # Skip these combinations because they have incompatible dependencies
    # and will always fail.
    - rvm: 2.6.0
      gemfile: gemfiles/rails_4.2_stable.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.2_stable.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_4.2_stable.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_4.2_stable.gemfile
  #    - rvm: 2.3
  #      gemfile: gemfiles/rails_6.0_beta.gemfile
  #    - rvm: 2.4
  #      gemfile: gemfiles/rails_6.0_beta.gemfile
  allow_failures:
#    - gemfile: gemfiles/rails_6.0_beta.gemfile
#    - rvm: ruby-head
gemfile:
  - gemfiles/rails_4.2_stable.gemfile
  - gemfiles/rails_5.0_stable.gemfile
  - gemfiles/rails_5.1_stable.gemfile
  - gemfiles/rails_5.2_stable.gemfile
#  - gemfiles/rails_6.0_beta.gemfile