language: ruby
before_install: gem install bundler -v '1.17.3'
install: bundle _1.17.3_ install --jobs=3 --retry=3
script: bundle exec rake
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head